class_name Level
extends Node2D
## Composes a map with a player and a camera.
##
## The map — tiles and markers — is generated by `tools/build_greybox.gd` and is
## regenerated wholesale. This sits above it and holds the things that are not
## map: where the player starts, where the camera may look, and whether the
## place is allowed to hurt you.
##
## Camera bounds are derived from the tiles rather than typed in, because a
## hand-maintained copy of the map's size is a number that silently goes stale
## the first time a room grows by one tile.

## The world lives inside a fixed-resolution SubViewport so the UI can sit
## outside it at the window's real resolution — see `ui/world_view.gd`. These
## paths are relative to that world root, not to this node.
@export var world_path: NodePath = ^"WorldView/SubViewport/World"

## The map scene instance holding the TileMapLayers.
@export var map_path: NodePath = ^"Map"
@export var player_path: NodePath = ^"Player"
@export var camera_path: NodePath = ^"CameraRig"

## Marker inside the map to start the player on. Falls back to the map centre.
@export var spawn_marker: String = "PlayerSpawn"

## Extra room beyond the tiles the camera may show, in pixels. A little slack
## stops the view snapping hard against the edge of the world.
@export var camera_margin: float = 0.0

## Safe locations set this. Ambry is mechanically incapable of hurting you and
## the player should feel that within ten seconds — no enemies, no timers, no
## fail states (GDD §7).
@export var is_safe: bool = true

## Instanced onto every `Doorways` marker the map carries. The map stays data —
## markers with metadata — and the level is what turns that data into nodes.
const DOORWAY_SCENE: PackedScene = preload("res://world/doorway.tscn")

## The same, for the walk-into edges of outdoor areas (`world/gateway.gd`).
const GATEWAY_SCENE: PackedScene = preload("res://world/gateway.tscn")

## ...and for the people. `NpcMarkers` carry an id; the id names both the body's
## tint and the conversation in `resources/dialogue/`.
const NPC_SCENE: PackedScene = preload("res://world/npc.tscn")

## ...and for what is lying on the ground. `PickupMarkers` carry a material id
## and an amount.
const PICKUP_SCENE: PackedScene = preload("res://world/pickup.tscn")

## ...and for the things that are not people. `EnemyMarkers` carry an
## `enemy_id`; the map says where and what, the scene says how it behaves.
const ENEMY_SCENES: Dictionary = {
	&"forest_wolf": preload("res://actors/enemies/forest_wolf/forest_wolf.tscn"),
	&"blighted_villager": preload("res://actors/enemies/blighted_villager/blighted_villager.tscn"),
}

## Real sprites for the villagers who have them. Everyone else falls back to the
## tinted rectangle below — which is the honest state of the art budget, not an
## oversight (GDD §8).
const NPC_ANIMATIONS: Dictionary = {
	&"fox": preload("res://resources/animation/fox.tres"),
}

## Drawn height per sprited villager, for the offset that puts their feet on the
## node origin. Printed by `tools/import_pixellab.py` at import time.
const NPC_HEIGHTS: Dictionary = {
	&"fox": 87.0,
}

## Placeholder body colours, keyed by npc id. Temporary in the obvious way — a
## real villager sheet replaces the whole idea — but six identical figures in one
## square reads as a bug rather than as a placeholder.
const NPC_TINTS: Dictionary = {
	&"carpenter": Color(0.80, 0.68, 0.46),
	&"child": Color(0.72, 0.80, 0.72),
	&"fox": Color(0.86, 0.58, 0.34),
	&"reluctant_guard": Color(0.58, 0.64, 0.74),
	&"unrepentant": Color(0.56, 0.52, 0.50),
	&"hidden_case": Color(0.46, 0.44, 0.48),
	&"magistrate": Color(0.70, 0.62, 0.72),
	&"smith": Color(0.78, 0.54, 0.44),
	&"innkeeper": Color(0.84, 0.74, 0.56),
	&"apothecary": Color(0.66, 0.78, 0.70),
	# Dyed wool, and a good one — she sells things and dresses like somebody who
	# does. The most saturated of the cast, which is still nowhere near the
	# blight's band (`tools/check_colour.py` guards that).
	&"shopkeeper": Color(0.74, 0.56, 0.62),
}

@onready var world: Node2D = get_node_or_null(world_path) as Node2D
@onready var map: Node2D = _in_world(map_path) as Node2D
@onready var player: Player = _in_world(player_path) as Player
@onready var camera: CameraRig = _in_world(camera_path) as CameraRig


func _in_world(path: NodePath) -> Node:
	return world.get_node_or_null(path) if world != null else null


func _ready() -> void:
	if map == null:
		push_warning("Level: no map at '%s'." % map_path)
		return

	var bounds := world_bounds()
	if camera != null and bounds.size != Vector2.ZERO:
		camera.apply_room_bounds(_frameable(bounds.grow(camera_margin)))

	place_player_at(spawn_marker)
	ensure_player_inside()
	_spawn_doorways()
	_spawn_gateways()
	_spawn_npcs()
	_spawn_enemies()
	_spawn_pickups()

	# Damage numbers are spawned here rather than by the hitbox, for the same
	# reason doorways are: the hitbox knows what it hit, but only the level knows
	# where the world node is — and a number parented to the thing it describes
	# would vanish with it the moment that thing died.
	Events.hit_landed.connect(_on_hit_landed)


## Put the player on a named marker and point the camera at them.
##
## Public because arriving is not only a start-of-scene event: `Doorway.travel`
## calls this *after* the save payload has been applied, since restoring a
## player also restores the position they had in the scene they just left.
func place_player_at(marker_name: String) -> bool:
	if player == null:
		return false
	var where := find_marker(marker_name)
	var found := where != Vector2.INF
	if not found:
		# Loud, because the fallback is a guess. A door pointing at a marker that
		# was renamed drops the player in the middle of the map, which looks like
		# a broken door rather than a broken name.
		push_warning("Level: no marker named '%s' in %s; using the map centre."
			% [marker_name, name])
		where = world_bounds().get_center()
	player.global_position = where
	if camera != null:
		camera.set_target(player)
	return found


## Put the player back on solid ground if something has left them outside the
## map, and say so.
##
## Two things can do that and neither raises an error on its own: a spawn marker
## that no longer exists, and a save whose stored position has nothing to do
## with this scene — `SaveGame.apply()` restores coordinates verbatim, because a
## save entry is data and it has no idea what map it is landing in.
##
## The symptom is the player standing in the void beyond the top-left corner
## with the camera unclamped, which reads as "the game spawned me wrong" and is
## invisible to every test that does not check coordinates. Better to correct it
## and leave a warning than to ship a game that occasionally starts you outside
## the world.
func ensure_player_inside() -> void:
	if player == null:
		return
	var bounds := world_bounds()
	if bounds.size == Vector2.ZERO or bounds.has_point(player.global_position):
		return

	var spawn := find_marker(spawn_marker)
	var rescued := spawn if spawn != Vector2.INF else bounds.get_center()
	push_warning("Level: player was at %s, outside %s — moved to %s."
		% [player.global_position, bounds, rescued])
	player.global_position = rescued
	if camera != null:
		camera.set_target(player)


func _spawn_doorways() -> void:
	var root := map.find_child("Doorways", true, false) if map != null else null
	if root == null:
		return
	for child in root.get_children():
		var marker := child as Marker2D
		if marker == null:
			continue
		var door: Doorway = DOORWAY_SCENE.instantiate()
		door.name = marker.name
		door.target_scene = String(marker.get_meta("target_scene", ""))
		door.target_spawn = String(marker.get_meta("target_spawn", "PlayerSpawn"))
		door.prompt = String(marker.get_meta("prompt", "Enter"))
		# Into the world, not onto this node — outside the SubViewport it would
		# be in window space and collide with nothing.
		world.add_child(door)
		door.global_position = marker.global_position


## The walk-into edges. Same shape as `_spawn_doorways`, different verb — see
## `world/gateway.gd` for why an edge is not a door.
func _spawn_gateways() -> void:
	var root := map.find_child("Gateways", true, false) if map != null else null
	if root == null:
		return
	for child in root.get_children():
		var marker := child as Marker2D
		if marker == null:
			continue
		var edge: Gateway = GATEWAY_SCENE.instantiate()
		edge.name = marker.name
		edge.target_scene = String(marker.get_meta("target_scene", ""))
		edge.target_spawn = String(marker.get_meta("target_spawn", "PlayerSpawn"))
		edge.facing = String(marker.get_meta("facing", "north"))
		edge.span = int(marker.get_meta("span", 4))
		world.add_child(edge)
		edge.global_position = marker.global_position


## The cast. Markers become bodies you can walk up to and talk to.
func _spawn_npcs() -> void:
	var root := map.find_child("NpcMarkers", true, false) if map != null else null
	if root == null:
		return
	for child in root.get_children():
		var marker := child as Marker2D
		if marker == null:
			continue
		var id := StringName(marker.get_meta("npc_id", ""))
		if id == &"":
			continue
		var person: Npc = NPC_SCENE.instantiate()
		person.name = "Npc_" + String(id)
		person.dialogue_id = id
		person.tint = NPC_TINTS.get(id, Color(0.78, 0.74, 0.66))
		person.animations = NPC_ANIMATIONS.get(id)
		person.body_height = float(NPC_HEIGHTS.get(id, 96.0))
		world.add_child(person)
		person.global_position = marker.global_position


## What is lying about in the world to be picked up.
##
## **This is the expedition.** GDD §15 A4 makes the town the progression system
## and the valley the place its materials come from; the carpenter's own line is
## "timber and stone, valley's full of both if you don't mind the walk". Until
## these existed that was a lie, and the loop the whole game is built on — go
## out, gather, come back, build — had no middle.
##
## Walked over rather than interacted with, deliberately: materials are the
## routine currency of a run and a button press forty times is a tax, not a
## decision. See `world/pickup.gd`.
func _spawn_pickups() -> void:
	var root := map.find_child("PickupMarkers", true, false) if map != null else null
	if root == null:
		return
	for child in root.get_children():
		var marker := child as Marker2D
		if marker == null:
			continue
		var id := StringName(marker.get_meta("material_id", ""))
		if id == &"":
			continue
		var loose: Pickup = PICKUP_SCENE.instantiate()
		loose.name = marker.name
		loose.material_id = id
		loose.amount = int(marker.get_meta("amount", 1))
		world.add_child(loose)
		loose.global_position = marker.global_position


## Throw a number off whatever was just hit.
##
## Coloured by who took it rather than who dealt it: the player reads "I lost
## two" and "it lost four" completely differently, and in the middle of a fight
## they are reading colour before they are reading digits.
func _on_hit_landed(_attacker: Node, target: Node, damage: int) -> void:
	if world == null or damage <= 0 or not (target is Node2D):
		return
	var body := target as Node2D
	# Above the middle of whatever it was, not at its feet.
	var lift := 48.0
	var animation := body.get_node_or_null("AnimationComponent") as AnimationComponent
	if animation != null:
		lift = animation.body_height * 0.75
	DamageNumber.pop(world, body.global_position - Vector2(0.0, lift), damage,
		target != player)


## Everything still lying about in this level.
func pickups() -> Array:
	var found: Array = []
	if world == null:
		return found
	for child in world.get_children():
		if child is Pickup:
			found.append(child)
	return found


## The things that are not people.
##
## **A safe level spawns nothing, whatever its map says.** GDD §7 wants Ambry to
## be mechanically incapable of hurting the player, and that is a stronger
## promise than "we did not put any enemies in the village" — it survives a
## marker pasted in by accident, a map regenerated with the wrong flag, and a
## builder change nobody reviewed. The village is safe because the code refuses,
## not because the data happens to be empty.
func _spawn_enemies() -> void:
	var root := map.find_child("EnemyMarkers", true, false) if map != null else null
	if root == null:
		return
	if is_safe:
		if root.get_child_count() > 0:
			push_warning("Level %s is marked safe; ignoring %d enemy markers."
				% [name, root.get_child_count()])
		return
	for child in root.get_children():
		var marker := child as Marker2D
		if marker == null:
			continue
		var id := StringName(marker.get_meta("enemy_id", ""))
		var scene: PackedScene = ENEMY_SCENES.get(id)
		if scene == null:
			push_warning("Level %s: no scene for enemy '%s'." % [name, id])
			continue
		var enemy: Node2D = scene.instantiate()
		enemy.name = marker.name
		world.add_child(enemy)
		enemy.global_position = marker.global_position


## Everything currently hunting in this level.
func enemies() -> Array:
	var found: Array = []
	if world == null:
		return found
	for child in world.get_children():
		if child is BaseEnemy:
			found.append(child)
	return found


## Everyone currently standing in this level, as {id, position}.
func npcs() -> Array:
	var found: Array = []
	if world == null:
		return found
	for child in world.get_children():
		var person := child as Npc
		if person != null:
			found.append({"id": person.dialogue_id, "position": person.global_position})
	return found


## Every gateway currently in the world, as {id, target, spawn, facing}. The
## tests walk these rather than hard-coding a map that is generated.
func gateways() -> Array:
	var found: Array = []
	if world == null:
		return found
	for child in world.get_children():
		var edge := child as Gateway
		if edge != null:
			found.append({
				"id": edge.name, "target": edge.target_scene,
				"spawn": edge.target_spawn, "facing": edge.facing,
			})
	return found


## Union of every TileMapLayer's used rect, in world pixels.
func world_bounds() -> Rect2:
	var bounds := Rect2()
	var first := true
	for layer in _layers():
		var used := layer.get_used_rect()
		if used.size == Vector2i.ZERO:
			continue
		var size: Vector2i = layer.tile_set.tile_size if layer.tile_set != null else Vector2i(64, 64)
		var rect := Rect2(Vector2(used.position * size), Vector2(used.size * size))
		rect.position += layer.global_position
		if first:
			bounds = rect
			first = false
		else:
			bounds = bounds.merge(rect)
	return bounds


## Camera limits smaller than the screen fight each other — the left limit
## pushes the view right and the right limit pushes it straight back — and the
## room ends up pinned to a corner instead of centred. A one-room interior is
## smaller than 1280×720, so the limit rect grows to at least a screen around
## the room's centre and the empty margin is allowed to show.
func _frameable(bounds: Rect2) -> Rect2:
	# The world's viewport, which is fixed at 1280x720, not the window — the
	# window's size is now a display concern and must not move the camera.
	var view := Vector2(WorldView.BASE)
	if world != null and world.get_viewport() != null:
		view = world.get_viewport().get_visible_rect().size
	var size := Vector2(maxf(bounds.size.x, view.x), maxf(bounds.size.y, view.y))
	return Rect2(bounds.get_center() - size * 0.5, size)


func _layers() -> Array[TileMapLayer]:
	var found: Array[TileMapLayer] = []
	if map == null:
		return found
	for child in map.get_children():
		var layer := child as TileMapLayer
		if layer != null:
			found.append(layer)
	return found


## World position of a named marker inside the map, or Vector2.INF.
func find_marker(marker_name: String) -> Vector2:
	if map == null or marker_name.is_empty():
		return Vector2.INF
	var node := map.find_child(marker_name, true, false) as Node2D
	return node.global_position if node != null else Vector2.INF


## Every building plot, as {id, state, district, position} — plus {project,
## cost, requires} on the ones that are rebuild projects. The rebuild system
## will read this; for now it is what makes the plots inspectable rather than
## decorative.
func building_plots() -> Array[Dictionary]:
	return _markers_under("BuildingPlots", "plot_id", ["state", "district"])


## Every permanent point of interest, as {id, note, district, position} —
## hearth, well, bell, gallows, gate, the breach. See docs/AMBRY.md.
func points_of_interest() -> Array[Dictionary]:
	return _markers_under("PointsOfInterest", "poi_id", ["note", "district"])


## Every placed NPC marker, as {id, position}.
func npc_markers() -> Array[Dictionary]:
	return _markers_under("NpcMarkers", "npc_id", [])


## A single POI or building plot by id, or an empty dictionary. Ids are unique
## across both — `home` is a plot, `bell` is a POI, and nothing is both.
func poi(id: String) -> Dictionary:
	for entry in points_of_interest() + building_plots():
		if String(entry.get("id", "")) == id:
			return entry
	return {}


## Which half of the village something is in: "south" (open from the start),
## "north" (behind the breach), "wall" (the breach itself, worked on from the
## south side), or "" if there is no such id here.
func district_of(id: String) -> String:
	return String(poi(id).get("district", ""))


## Every rebuild project placed in this level, as its plot or POI entry.
func rebuild_projects() -> Array[Dictionary]:
	var found: Array[Dictionary] = []
	for entry in points_of_interest() + building_plots():
		if bool(entry.get("project", false)):
			found.append(entry)
	return found


## Markers under a named group node, with `id_key` read as `id` and each of
## `extra_keys` copied across when present. Project metadata comes along
## automatically, so adding a field to the build script does not mean editing
## a reader here as well.
func _markers_under(group_name: String, id_key: String, extra_keys: Array) -> Array[Dictionary]:
	var markers: Array[Dictionary] = []
	if map == null:
		return markers
	var root := map.find_child(group_name, true, false)
	if root == null:
		return markers
	for child in root.get_children():
		var marker := child as Marker2D
		if marker == null:
			continue
		var entry := {
			"id": marker.get_meta(id_key, marker.name),
			"position": marker.global_position,
		}
		for key in extra_keys:
			entry[key] = marker.get_meta(key, "")
		for key in ["project", "cost", "requires"]:
			if marker.has_meta(key):
				entry[key] = marker.get_meta(key)
		markers.append(entry)
	return markers
