class_name Level
extends Node2D
## Composes a map with a player and a camera.
##
## The map — tiles and markers — is generated by `tools/build_greybox.gd` and is
## regenerated wholesale. This sits above it and holds the things that are not
## map: where the player starts, where the camera may look, and whether the
## place is allowed to hurt you.
##
## Camera bounds are derived from the tiles rather than typed in, because a
## hand-maintained copy of the map's size is a number that silently goes stale
## the first time a room grows by one tile.

## The map scene instance holding the TileMapLayers.
@export var map_path: NodePath = ^"Map"
@export var player_path: NodePath = ^"Player"
@export var camera_path: NodePath = ^"CameraRig"

## Marker inside the map to start the player on. Falls back to the map centre.
@export var spawn_marker: String = "PlayerSpawn"

## Extra room beyond the tiles the camera may show, in pixels. A little slack
## stops the view snapping hard against the edge of the world.
@export var camera_margin: float = 0.0

## Safe locations set this. Ambry is mechanically incapable of hurting you and
## the player should feel that within ten seconds — no enemies, no timers, no
## fail states (GDD §7).
@export var is_safe: bool = true

@onready var map: Node2D = get_node_or_null(map_path) as Node2D
@onready var player: Player = get_node_or_null(player_path) as Player
@onready var camera: CameraRig = get_node_or_null(camera_path) as CameraRig


func _ready() -> void:
	if map == null:
		push_warning("Level: no map at '%s'." % map_path)
		return

	var bounds := world_bounds()
	if camera != null and bounds.size != Vector2.ZERO:
		camera.apply_room_bounds(bounds.grow(camera_margin))

	if player != null:
		var spawn := find_marker(spawn_marker)
		player.global_position = spawn if spawn != Vector2.INF else bounds.get_center()
		if camera != null:
			camera.set_target(player)


## Union of every TileMapLayer's used rect, in world pixels.
func world_bounds() -> Rect2:
	var bounds := Rect2()
	var first := true
	for layer in _layers():
		var used := layer.get_used_rect()
		if used.size == Vector2i.ZERO:
			continue
		var size: Vector2i = layer.tile_set.tile_size if layer.tile_set != null else Vector2i(64, 64)
		var rect := Rect2(Vector2(used.position * size), Vector2(used.size * size))
		rect.position += layer.global_position
		if first:
			bounds = rect
			first = false
		else:
			bounds = bounds.merge(rect)
	return bounds


func _layers() -> Array[TileMapLayer]:
	var found: Array[TileMapLayer] = []
	if map == null:
		return found
	for child in map.get_children():
		var layer := child as TileMapLayer
		if layer != null:
			found.append(layer)
	return found


## World position of a named marker inside the map, or Vector2.INF.
func find_marker(marker_name: String) -> Vector2:
	if map == null or marker_name.is_empty():
		return Vector2.INF
	var node := map.find_child(marker_name, true, false) as Node2D
	return node.global_position if node != null else Vector2.INF


## Every building plot, as {id, state, position}. The rebuild system will read
## this; for now it is what makes the plots inspectable rather than decorative.
func building_plots() -> Array[Dictionary]:
	var plots: Array[Dictionary] = []
	if map == null:
		return plots
	var root := map.find_child("BuildingPlots", true, false)
	if root == null:
		return plots
	for child in root.get_children():
		var marker := child as Marker2D
		if marker == null:
			continue
		plots.append({
			"id": marker.get_meta("plot_id", marker.name),
			"state": marker.get_meta("state", "empty"),
			"position": marker.global_position,
		})
	return plots


## Every placed NPC marker, as {id, position}.
func npc_markers() -> Array[Dictionary]:
	var markers: Array[Dictionary] = []
	if map == null:
		return markers
	var root := map.find_child("NpcMarkers", true, false)
	if root == null:
		return markers
	for child in root.get_children():
		var marker := child as Marker2D
		if marker == null:
			continue
		markers.append({
			"id": marker.get_meta("npc_id", marker.name),
			"position": marker.global_position,
		})
	return markers
