#!/usr/bin/env python3
"""Write an ActorAnimationSet .tres from whatever strips are on disk.

    python3 tools/build_animation_set.py player
    python3 tools/build_animation_set.py forest_wolf --out resources/animation/forest_wolf.tres
    python3 tools/build_animation_set.py player --frames idle=2,walk=6

An eight-direction actor is up to 64 texture references spread across seven
clips. Hand-authoring that .tres is an hour of clerical work in which exactly
one typo produces a character who walks north-west facing south, and finding it
means reading the file rather than playing the game. So it is generated.

**The directory is the source of truth.** This reads
`art/sprites/<actor>/<actor>_<clip>_<direction>.png` and writes a set
containing precisely the strips that exist. Add a direction later and re-run;
nothing else changes. A missing strip is not an error — `SpriteAnimation`
resolves it through its fallback chain, which is what lets a three-strip actor
and an eight-strip actor share one component.

Frame counts are inferred as `width / height`, i.e. square frames. That holds
for every actor in the project (128x128 for the player, 96x96 for the wolf).
Override with `--frames clip=n,clip=n` for anything that is not square.
"""

from __future__ import annotations

import argparse
import os
import struct
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Slot name in SpriteAnimation -> filename suffix. Order matters only for the
# report; the resolve chain lives in GDScript.
DIRECTIONS = [
    "down",
    "up",
    "side",
    "down_side",
    "up_side",
    "side_west",
    "down_side_west",
    "up_side_west",
]

# Slot in ActorAnimationSet -> (default fps, loops).
#
# Attacks get fps 0 deliberately: they are advanced by PlayerAttackState against
# ComboStepData's phase boundaries, never by a clock. A non-zero fps there is a
# swing whose picture finishes before its own hitbox does.
CLIPS = {
    "idle": (3.0, True),
    "walk": (10.0, True),
    "attack_1": (0.0, False),
    "attack_2": (0.0, False),
    "attack_3": (0.0, False),
    "dodge": (11.0, False),
    "hurt": (1.0, False),
    "death": (10.0, False),
}


def png_size(path: str) -> tuple[int, int]:
    with open(path, "rb") as handle:
        head = handle.read(24)
    if head[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError(f"{path}: not a PNG")
    return struct.unpack(">II", head[16:24])


def collect(actor: str, overrides: dict[str, int]) -> dict:
    folder = os.path.join(ROOT, "art", "sprites", actor)
    if not os.path.isdir(folder):
        sys.exit(f"no such directory: {os.path.relpath(folder, ROOT)}")

    found: dict[str, dict] = {}
    for clip, (fps, loop) in CLIPS.items():
        strips: dict[str, str] = {}
        frames = 0
        height = 0
        for direction in DIRECTIONS:
            name = f"{actor}_{clip}_{direction}.png"
            path = os.path.join(folder, name)
            if not os.path.isfile(path):
                continue
            width, tall = png_size(path)
            count = overrides.get(clip, max(width // tall, 1) if tall else 1)
            if frames and count != frames:
                print(f"  ! {name}: {count} frames, but {clip} is {frames} elsewhere")
            if height and tall != height:
                print(f"  ! {name}: {tall}px tall, but {clip} is {height}px elsewhere")
            frames, height = count, tall
            strips[direction] = f"res://art/sprites/{actor}/{name}"
        if strips:
            found[clip] = {"strips": strips, "frames": frames, "fps": fps, "loop": loop}
    return found


def render(actor: str, clips: dict) -> str:
    externals: dict[str, str] = {}
    for clip, info in clips.items():
        for direction, path in info["strips"].items():
            externals[path] = f"{len(externals) + 3}_{clip}_{direction}"

    lines = [
        "; Generated by tools/build_animation_set.py — do not hand-edit.",
        "; Re-run after adding or replacing a strip in art/sprites/%s/." % actor,
        "",
        '[gd_resource type="Resource" script_class="ActorAnimationSet" '
        f'load_steps={len(externals) + len(clips) + 3} format=3]',
        "",
        '[ext_resource type="Script" path="res://resources/animation/'
        'actor_animation_set.gd" id="1_set"]',
        '[ext_resource type="Script" path="res://resources/animation/'
        'sprite_animation.gd" id="2_clip"]',
    ]
    for path, ident in externals.items():
        lines.append(f'[ext_resource type="Texture2D" path="{path}" id="{ident}"]')

    for clip, info in clips.items():
        lines += [
            "",
            f'[sub_resource type="Resource" id="Res_{clip}"]',
            f'resource_name = "{clip}"',
            'script = ExtResource("2_clip")',
        ]
        for direction in DIRECTIONS:
            path = info["strips"].get(direction)
            if path:
                lines.append(f'{direction} = ExtResource("{externals[path]}")')
        lines += [
            f"frames = {info['frames']}",
            f"fps = {info['fps']}",
            f"loop = {'true' if info['loop'] else 'false'}",
        ]

    lines += [
        "",
        "[resource]",
        f'resource_name = "{actor} animations"',
        'script = ExtResource("1_set")',
    ]
    for clip in CLIPS:
        if clip in clips:
            lines.append(f'{clip} = SubResource("Res_{clip}")')
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("actor", help="folder under art/sprites/ and the filename prefix")
    parser.add_argument("--out", help="defaults to resources/animation/<actor>.tres")
    parser.add_argument("--frames", default="", help="clip=n,clip=n for non-square frames")
    args = parser.parse_args()

    overrides = {}
    for pair in filter(None, args.frames.split(",")):
        clip, _, count = pair.partition("=")
        overrides[clip.strip()] = int(count)

    clips = collect(args.actor, overrides)
    if not clips:
        sys.exit(f"no strips found matching art/sprites/{args.actor}/{args.actor}_<clip>_<dir>.png")

    out = args.out or os.path.join("resources", "animation", f"{args.actor}.tres")
    path = out if os.path.isabs(out) else os.path.join(ROOT, out)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(render(args.actor, clips))

    print(f"{args.actor}: {len(clips)} clips -> {os.path.relpath(path, ROOT)}")
    for clip, info in clips.items():
        have = [d for d in DIRECTIONS if d in info["strips"]]
        missing = [d for d in DIRECTIONS if d not in info["strips"]]
        note = f"  (falls back for {', '.join(missing)})" if missing else ""
        print(f"  {clip:<9} {info['frames']} frames, {len(have)}/8 directions{note}")


if __name__ == "__main__":
    main()
